services:
  - type: web
    name: streammedia-torrent-streamer
    runtime: node
    plan: free
    region: oregon
    rootDir: tools/torrent-streamer
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
